/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Backend API
 * API for IoT Dashboard
 * OpenAPI spec version: 1.0.0
 */
import type {
  DeleteApiLogs200,
  DeleteApiModulesIdZone200,
  GetApiDbSize200,
  GetApiLogs200,
  GetApiLogsHistogram200Item,
  GetApiLogsHistogramParams,
  GetApiLogsParams,
  GetApiMetricsHistory200,
  GetApiMetricsHistoryParams,
  GetApiModules200Item,
  GetApiModulesIdData200,
  GetApiModulesIdDataParams,
  GetApiModulesIdHistory200,
  GetApiModulesIdHistoryParams,
  GetApiModulesIdStatus200,
  GetApiModulesIdStorage200,
  GetApiModulesTypes200Item,
  GetApiModulesTypesTypeManifest200,
  GetApiZones200Item,
  GetApiZonesId200,
  PatchApiModulesIdPreferences200,
  PatchApiModulesIdPreferencesBody,
  PostApiModulesIdConfig200,
  PostApiModulesIdConfigBody,
  PostApiModulesIdResetSensor200,
  PostApiModulesIdResetSensorBody,
  PostApiZones201,
  PostApiZonesBody,
  PutApiZonesId200,
  PutApiZonesIdBody
} from './model';


/**
 * @summary List all modules
 */
export type getApiModulesResponse200 = {
  data: GetApiModules200Item[]
  status: 200
}
    
export type getApiModulesResponseSuccess = (getApiModulesResponse200) & {
  headers: Headers;
};
;

export type getApiModulesResponse = (getApiModulesResponseSuccess)

export const getGetApiModulesUrl = () => {


  

  return `http://localhost:3001/api/modules`
}

export const getApiModules = async ( options?: RequestInit): Promise<getApiModulesResponse> => {
  
  const res = await fetch(getGetApiModulesUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getApiModulesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiModulesResponse
}



/**
 * @summary Update module sensor configuration
 */
export type postApiModulesIdConfigResponse200 = {
  data: PostApiModulesIdConfig200
  status: 200
}
    
export type postApiModulesIdConfigResponseSuccess = (postApiModulesIdConfigResponse200) & {
  headers: Headers;
};
;

export type postApiModulesIdConfigResponse = (postApiModulesIdConfigResponseSuccess)

export const getPostApiModulesIdConfigUrl = (id: string,) => {


  

  return `http://localhost:3001/api/modules/${id}/config`
}

export const postApiModulesIdConfig = async (id: string,
    postApiModulesIdConfigBody: PostApiModulesIdConfigBody, options?: RequestInit): Promise<postApiModulesIdConfigResponse> => {
  
  const res = await fetch(getPostApiModulesIdConfigUrl(id),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postApiModulesIdConfigBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postApiModulesIdConfigResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postApiModulesIdConfigResponse
}



/**
 * @summary Reset a specific sensor
 */
export type postApiModulesIdResetSensorResponse200 = {
  data: PostApiModulesIdResetSensor200
  status: 200
}
    
export type postApiModulesIdResetSensorResponseSuccess = (postApiModulesIdResetSensorResponse200) & {
  headers: Headers;
};
;

export type postApiModulesIdResetSensorResponse = (postApiModulesIdResetSensorResponseSuccess)

export const getPostApiModulesIdResetSensorUrl = (id: string,) => {


  

  return `http://localhost:3001/api/modules/${id}/reset-sensor`
}

export const postApiModulesIdResetSensor = async (id: string,
    postApiModulesIdResetSensorBody: PostApiModulesIdResetSensorBody, options?: RequestInit): Promise<postApiModulesIdResetSensorResponse> => {
  
  const res = await fetch(getPostApiModulesIdResetSensorUrl(id),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postApiModulesIdResetSensorBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postApiModulesIdResetSensorResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postApiModulesIdResetSensorResponse
}



/**
 * @summary Update module preferences
 */
export type patchApiModulesIdPreferencesResponse200 = {
  data: PatchApiModulesIdPreferences200
  status: 200
}
    
export type patchApiModulesIdPreferencesResponseSuccess = (patchApiModulesIdPreferencesResponse200) & {
  headers: Headers;
};
;

export type patchApiModulesIdPreferencesResponse = (patchApiModulesIdPreferencesResponseSuccess)

export const getPatchApiModulesIdPreferencesUrl = (id: string,) => {


  

  return `http://localhost:3001/api/modules/${id}/preferences`
}

export const patchApiModulesIdPreferences = async (id: string,
    patchApiModulesIdPreferencesBody: PatchApiModulesIdPreferencesBody, options?: RequestInit): Promise<patchApiModulesIdPreferencesResponse> => {
  
  const res = await fetch(getPatchApiModulesIdPreferencesUrl(id),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      patchApiModulesIdPreferencesBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: patchApiModulesIdPreferencesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as patchApiModulesIdPreferencesResponse
}



/**
 * @summary Remove device from its zone
 */
export type deleteApiModulesIdZoneResponse200 = {
  data: DeleteApiModulesIdZone200
  status: 200
}
    
export type deleteApiModulesIdZoneResponseSuccess = (deleteApiModulesIdZoneResponse200) & {
  headers: Headers;
};
;

export type deleteApiModulesIdZoneResponse = (deleteApiModulesIdZoneResponseSuccess)

export const getDeleteApiModulesIdZoneUrl = (id: string,) => {


  

  return `http://localhost:3001/api/modules/${id}/zone`
}

export const deleteApiModulesIdZone = async (id: string, options?: RequestInit): Promise<deleteApiModulesIdZoneResponse> => {
  
  const res = await fetch(getDeleteApiModulesIdZoneUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: deleteApiModulesIdZoneResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteApiModulesIdZoneResponse
}



/**
 * @summary Get module status (system, hardware, sensors config)
 */
export type getApiModulesIdStatusResponse200 = {
  data: GetApiModulesIdStatus200
  status: 200
}
    
export type getApiModulesIdStatusResponseSuccess = (getApiModulesIdStatusResponse200) & {
  headers: Headers;
};
;

export type getApiModulesIdStatusResponse = (getApiModulesIdStatusResponseSuccess)

export const getGetApiModulesIdStatusUrl = (id: string,) => {


  

  return `http://localhost:3001/api/modules/${id}/status`
}

export const getApiModulesIdStatus = async (id: string, options?: RequestInit): Promise<getApiModulesIdStatusResponse> => {
  
  const res = await fetch(getGetApiModulesIdStatusUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getApiModulesIdStatusResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiModulesIdStatusResponse
}



/**
 * @summary Get historical sensor data
 */
export type getApiModulesIdHistoryResponse200 = {
  data: GetApiModulesIdHistory200
  status: 200
}
    
export type getApiModulesIdHistoryResponseSuccess = (getApiModulesIdHistoryResponse200) & {
  headers: Headers;
};
;

export type getApiModulesIdHistoryResponse = (getApiModulesIdHistoryResponseSuccess)

export const getGetApiModulesIdHistoryUrl = (id: string,
    params?: GetApiModulesIdHistoryParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:3001/api/modules/${id}/history?${stringifiedParams}` : `http://localhost:3001/api/modules/${id}/history`
}

export const getApiModulesIdHistory = async (id: string,
    params?: GetApiModulesIdHistoryParams, options?: RequestInit): Promise<getApiModulesIdHistoryResponse> => {
  
  const res = await fetch(getGetApiModulesIdHistoryUrl(id,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getApiModulesIdHistoryResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiModulesIdHistoryResponse
}



/**
 * @summary Get module storage statistics and projections
 */
export type getApiModulesIdStorageResponse200 = {
  data: GetApiModulesIdStorage200
  status: 200
}
    
export type getApiModulesIdStorageResponseSuccess = (getApiModulesIdStorageResponse200) & {
  headers: Headers;
};
;

export type getApiModulesIdStorageResponse = (getApiModulesIdStorageResponseSuccess)

export const getGetApiModulesIdStorageUrl = (id: string,) => {


  

  return `http://localhost:3001/api/modules/${id}/storage`
}

export const getApiModulesIdStorage = async (id: string, options?: RequestInit): Promise<getApiModulesIdStorageResponse> => {
  
  const res = await fetch(getGetApiModulesIdStorageUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getApiModulesIdStorageResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiModulesIdStorageResponse
}



/**
 * @summary [Legacy] Get module status and time series measurements
 */
export type getApiModulesIdDataResponse200 = {
  data: GetApiModulesIdData200
  status: 200
}
    
export type getApiModulesIdDataResponseSuccess = (getApiModulesIdDataResponse200) & {
  headers: Headers;
};
;

export type getApiModulesIdDataResponse = (getApiModulesIdDataResponseSuccess)

export const getGetApiModulesIdDataUrl = (id: string,
    params?: GetApiModulesIdDataParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:3001/api/modules/${id}/data?${stringifiedParams}` : `http://localhost:3001/api/modules/${id}/data`
}

export const getApiModulesIdData = async (id: string,
    params?: GetApiModulesIdDataParams, options?: RequestInit): Promise<getApiModulesIdDataResponse> => {
  
  const res = await fetch(getGetApiModulesIdDataUrl(id,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getApiModulesIdDataResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiModulesIdDataResponse
}



/**
 * @summary Get database size
 */
export type getApiDbSizeResponse200 = {
  data: GetApiDbSize200
  status: 200
}
    
export type getApiDbSizeResponseSuccess = (getApiDbSizeResponse200) & {
  headers: Headers;
};
;

export type getApiDbSizeResponse = (getApiDbSizeResponseSuccess)

export const getGetApiDbSizeUrl = () => {


  

  return `http://localhost:3001/api/db-size`
}

export const getApiDbSize = async ( options?: RequestInit): Promise<getApiDbSizeResponse> => {
  
  const res = await fetch(getGetApiDbSizeUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getApiDbSizeResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiDbSizeResponse
}



/**
 * @summary Get system metrics history
 */
export type getApiMetricsHistoryResponse200 = {
  data: GetApiMetricsHistory200
  status: 200
}
    
export type getApiMetricsHistoryResponseSuccess = (getApiMetricsHistoryResponse200) & {
  headers: Headers;
};
;

export type getApiMetricsHistoryResponse = (getApiMetricsHistoryResponseSuccess)

export const getGetApiMetricsHistoryUrl = (params?: GetApiMetricsHistoryParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:3001/api/metrics-history?${stringifiedParams}` : `http://localhost:3001/api/metrics-history`
}

export const getApiMetricsHistory = async (params?: GetApiMetricsHistoryParams, options?: RequestInit): Promise<getApiMetricsHistoryResponse> => {
  
  const res = await fetch(getGetApiMetricsHistoryUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getApiMetricsHistoryResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiMetricsHistoryResponse
}



/**
 * @summary List all available module types
 */
export type getApiModulesTypesResponse200 = {
  data: GetApiModulesTypes200Item[]
  status: 200
}
    
export type getApiModulesTypesResponseSuccess = (getApiModulesTypesResponse200) & {
  headers: Headers;
};
;

export type getApiModulesTypesResponse = (getApiModulesTypesResponseSuccess)

export const getGetApiModulesTypesUrl = () => {


  

  return `http://localhost:3001/api/modules/types`
}

export const getApiModulesTypes = async ( options?: RequestInit): Promise<getApiModulesTypesResponse> => {
  
  const res = await fetch(getGetApiModulesTypesUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getApiModulesTypesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiModulesTypesResponse
}



/**
 * @summary Get full manifest for a module type
 */
export type getApiModulesTypesTypeManifestResponse200 = {
  data: GetApiModulesTypesTypeManifest200
  status: 200
}
    
export type getApiModulesTypesTypeManifestResponseSuccess = (getApiModulesTypesTypeManifestResponse200) & {
  headers: Headers;
};
;

export type getApiModulesTypesTypeManifestResponse = (getApiModulesTypesTypeManifestResponseSuccess)

export const getGetApiModulesTypesTypeManifestUrl = (type: string,) => {


  

  return `http://localhost:3001/api/modules/types/${type}/manifest`
}

export const getApiModulesTypesTypeManifest = async (type: string, options?: RequestInit): Promise<getApiModulesTypesTypeManifestResponse> => {
  
  const res = await fetch(getGetApiModulesTypesTypeManifestUrl(type),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getApiModulesTypesTypeManifestResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiModulesTypesTypeManifestResponse
}



/**
 * @summary List all zones
 */
export type getApiZonesResponse200 = {
  data: GetApiZones200Item[]
  status: 200
}
    
export type getApiZonesResponseSuccess = (getApiZonesResponse200) & {
  headers: Headers;
};
;

export type getApiZonesResponse = (getApiZonesResponseSuccess)

export const getGetApiZonesUrl = () => {


  

  return `http://localhost:3001/api/zones`
}

export const getApiZones = async ( options?: RequestInit): Promise<getApiZonesResponse> => {
  
  const res = await fetch(getGetApiZonesUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getApiZonesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiZonesResponse
}



/**
 * @summary Create a new zone
 */
export type postApiZonesResponse201 = {
  data: PostApiZones201
  status: 201
}
    
export type postApiZonesResponseSuccess = (postApiZonesResponse201) & {
  headers: Headers;
};
;

export type postApiZonesResponse = (postApiZonesResponseSuccess)

export const getPostApiZonesUrl = () => {


  

  return `http://localhost:3001/api/zones`
}

export const postApiZones = async (postApiZonesBody: PostApiZonesBody, options?: RequestInit): Promise<postApiZonesResponse> => {
  
  const res = await fetch(getPostApiZonesUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postApiZonesBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postApiZonesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postApiZonesResponse
}



/**
 * @summary Get zone with its devices
 */
export type getApiZonesIdResponse200 = {
  data: GetApiZonesId200
  status: 200
}
    
export type getApiZonesIdResponseSuccess = (getApiZonesIdResponse200) & {
  headers: Headers;
};
;

export type getApiZonesIdResponse = (getApiZonesIdResponseSuccess)

export const getGetApiZonesIdUrl = (id: string,) => {


  

  return `http://localhost:3001/api/zones/${id}`
}

export const getApiZonesId = async (id: string, options?: RequestInit): Promise<getApiZonesIdResponse> => {
  
  const res = await fetch(getGetApiZonesIdUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getApiZonesIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiZonesIdResponse
}



/**
 * @summary Update zone name
 */
export type putApiZonesIdResponse200 = {
  data: PutApiZonesId200
  status: 200
}
    
export type putApiZonesIdResponseSuccess = (putApiZonesIdResponse200) & {
  headers: Headers;
};
;

export type putApiZonesIdResponse = (putApiZonesIdResponseSuccess)

export const getPutApiZonesIdUrl = (id: string,) => {


  

  return `http://localhost:3001/api/zones/${id}`
}

export const putApiZonesId = async (id: string,
    putApiZonesIdBody: PutApiZonesIdBody, options?: RequestInit): Promise<putApiZonesIdResponse> => {
  
  const res = await fetch(getPutApiZonesIdUrl(id),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      putApiZonesIdBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: putApiZonesIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as putApiZonesIdResponse
}



/**
 * @summary Delete zone (devices are unassigned)
 */
export type deleteApiZonesIdResponse200 = {
  data: void
  status: 200
}
    
export type deleteApiZonesIdResponseSuccess = (deleteApiZonesIdResponse200) & {
  headers: Headers;
};
;

export type deleteApiZonesIdResponse = (deleteApiZonesIdResponseSuccess)

export const getDeleteApiZonesIdUrl = (id: string,) => {


  

  return `http://localhost:3001/api/zones/${id}`
}

export const deleteApiZonesId = async (id: string, options?: RequestInit): Promise<deleteApiZonesIdResponse> => {
  
  const res = await fetch(getDeleteApiZonesIdUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: deleteApiZonesIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteApiZonesIdResponse
}



/**
 * @summary Assign a device to this zone
 */
export type postApiZonesIdDevicesDeviceIdResponse200 = {
  data: void
  status: 200
}
    
export type postApiZonesIdDevicesDeviceIdResponseSuccess = (postApiZonesIdDevicesDeviceIdResponse200) & {
  headers: Headers;
};
;

export type postApiZonesIdDevicesDeviceIdResponse = (postApiZonesIdDevicesDeviceIdResponseSuccess)

export const getPostApiZonesIdDevicesDeviceIdUrl = (id: string,
    deviceId: string,) => {


  

  return `http://localhost:3001/api/zones/${id}/devices/${deviceId}`
}

export const postApiZonesIdDevicesDeviceId = async (id: string,
    deviceId: string, options?: RequestInit): Promise<postApiZonesIdDevicesDeviceIdResponse> => {
  
  const res = await fetch(getPostApiZonesIdDevicesDeviceIdUrl(id,deviceId),
  {      
    ...options,
    method: 'POST'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postApiZonesIdDevicesDeviceIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postApiZonesIdDevicesDeviceIdResponse
}



/**
 * @summary Remove a device from this zone
 */
export type deleteApiZonesIdDevicesDeviceIdResponse200 = {
  data: void
  status: 200
}
    
export type deleteApiZonesIdDevicesDeviceIdResponseSuccess = (deleteApiZonesIdDevicesDeviceIdResponse200) & {
  headers: Headers;
};
;

export type deleteApiZonesIdDevicesDeviceIdResponse = (deleteApiZonesIdDevicesDeviceIdResponseSuccess)

export const getDeleteApiZonesIdDevicesDeviceIdUrl = (id: string,
    deviceId: string,) => {


  

  return `http://localhost:3001/api/zones/${id}/devices/${deviceId}`
}

export const deleteApiZonesIdDevicesDeviceId = async (id: string,
    deviceId: string, options?: RequestInit): Promise<deleteApiZonesIdDevicesDeviceIdResponse> => {
  
  const res = await fetch(getDeleteApiZonesIdDevicesDeviceIdUrl(id,deviceId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: deleteApiZonesIdDevicesDeviceIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteApiZonesIdDevicesDeviceIdResponse
}



/**
 * @summary Get system logs with filtering
 */
export type getApiLogsResponse200 = {
  data: GetApiLogs200
  status: 200
}
    
export type getApiLogsResponseSuccess = (getApiLogsResponse200) & {
  headers: Headers;
};
;

export type getApiLogsResponse = (getApiLogsResponseSuccess)

export const getGetApiLogsUrl = (params?: GetApiLogsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:3001/api/logs?${stringifiedParams}` : `http://localhost:3001/api/logs`
}

export const getApiLogs = async (params?: GetApiLogsParams, options?: RequestInit): Promise<getApiLogsResponse> => {
  
  const res = await fetch(getGetApiLogsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getApiLogsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiLogsResponse
}



/**
 * @summary Delete all system logs
 */
export type deleteApiLogsResponse200 = {
  data: DeleteApiLogs200
  status: 200
}
    
export type deleteApiLogsResponseSuccess = (deleteApiLogsResponse200) & {
  headers: Headers;
};
;

export type deleteApiLogsResponse = (deleteApiLogsResponseSuccess)

export const getDeleteApiLogsUrl = () => {


  

  return `http://localhost:3001/api/logs`
}

export const deleteApiLogs = async ( options?: RequestInit): Promise<deleteApiLogsResponse> => {
  
  const res = await fetch(getDeleteApiLogsUrl(),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: deleteApiLogsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteApiLogsResponse
}



/**
 * @summary Get system logs histogram data
 */
export type getApiLogsHistogramResponse200 = {
  data: GetApiLogsHistogram200Item[]
  status: 200
}
    
export type getApiLogsHistogramResponseSuccess = (getApiLogsHistogramResponse200) & {
  headers: Headers;
};
;

export type getApiLogsHistogramResponse = (getApiLogsHistogramResponseSuccess)

export const getGetApiLogsHistogramUrl = (params?: GetApiLogsHistogramParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:3001/api/logs/histogram?${stringifiedParams}` : `http://localhost:3001/api/logs/histogram`
}

export const getApiLogsHistogram = async (params?: GetApiLogsHistogramParams, options?: RequestInit): Promise<getApiLogsHistogramResponse> => {
  
  const res = await fetch(getGetApiLogsHistogramUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getApiLogsHistogramResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiLogsHistogramResponse
}



export type getHealthResponse200 = {
  data: void
  status: 200
}
    
export type getHealthResponseSuccess = (getHealthResponse200) & {
  headers: Headers;
};
;

export type getHealthResponse = (getHealthResponseSuccess)

export const getGetHealthUrl = () => {


  

  return `http://localhost:3001/health`
}

export const getHealth = async ( options?: RequestInit): Promise<getHealthResponse> => {
  
  const res = await fetch(getGetHealthUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getHealthResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getHealthResponse
}



