/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Backend API
 * API for IoT Dashboard
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiModulesIdData200SensorsPm10ItemTime } from './getApiModulesIdData200SensorsPm10ItemTime';

export type GetApiModulesIdData200SensorsPm10Item = {
  time: GetApiModulesIdData200SensorsPm10ItemTime;
  value: number;
};
