/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Backend API
 * API for IoT Dashboard
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiModulesIdHistory200TemperatureBmpItemTime } from './getApiModulesIdHistory200TemperatureBmpItemTime';

export type GetApiModulesIdHistory200TemperatureBmpItem = {
  time: GetApiModulesIdHistory200TemperatureBmpItemTime;
  value: number;
};
