/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Backend API
 * API for IoT Dashboard
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiLogsHistogramCategoryAnyOfItem } from './getApiLogsHistogramCategoryAnyOfItem';
import type { GetApiLogsHistogramLevelAnyOfItem } from './getApiLogsHistogramLevelAnyOfItem';

export type GetApiLogsHistogramParams = {
/**
 * @pattern ^\d{4}-\d{2}-\d{2}$
 */
date?: string;
startDate?: string;
endDate?: string;
category?: 'HARDWARE' | 'MQTT' | 'DB' | 'API' | 'SYSTEM' | 'WEBSOCKET' | GetApiLogsHistogramCategoryAnyOfItem[];
level?: 'trace' | 'debug' | 'success' | 'info' | 'warn' | 'error' | 'fatal' | GetApiLogsHistogramLevelAnyOfItem[];
search?: string;
};
