/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Backend API
 * API for IoT Dashboard
 * OpenAPI spec version: 1.0.0
 */

export type GetApiLogsHistogramCategoryAnyOfItem = typeof GetApiLogsHistogramCategoryAnyOfItem[keyof typeof GetApiLogsHistogramCategoryAnyOfItem];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiLogsHistogramCategoryAnyOfItem = {
  HARDWARE: 'HARDWARE',
  MQTT: 'MQTT',
  DB: 'DB',
  API: 'API',
  SYSTEM: 'SYSTEM',
  WEBSOCKET: 'WEBSOCKET',
} as const;
