/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Backend API
 * API for IoT Dashboard
 * OpenAPI spec version: 1.0.0
 */

export type GetApiModulesTypesTypeManifest200ActionsItemScope = typeof GetApiModulesTypesTypeManifest200ActionsItemScope[keyof typeof GetApiModulesTypesTypeManifest200ActionsItemScope];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiModulesTypesTypeManifest200ActionsItemScope = {
  sensor: 'sensor',
  hardware: 'hardware',
  device: 'device',
} as const;
