/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Backend API
 * API for IoT Dashboard
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiModulesIdHistory200TvocItemTime } from './getApiModulesIdHistory200TvocItemTime';

export type GetApiModulesIdHistory200TvocItem = {
  time: GetApiModulesIdHistory200TvocItemTime;
  value: number;
};
