/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Backend API
 * API for IoT Dashboard
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiModulesIdStatus200SensorsConfigSensors } from './getApiModulesIdStatus200SensorsConfigSensors';

export type GetApiModulesIdStatus200SensorsConfig = {
  sensors: GetApiModulesIdStatus200SensorsConfigSensors;
};
