/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Backend API
 * API for IoT Dashboard
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiModulesIdData200SensorsPm1ItemTime } from './getApiModulesIdData200SensorsPm1ItemTime';

export type GetApiModulesIdData200SensorsPm1Item = {
  time: GetApiModulesIdData200SensorsPm1ItemTime;
  value: number;
};
