/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Backend API
 * API for IoT Dashboard
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiModulesIdData200SensorsTvocItemTime } from './getApiModulesIdData200SensorsTvocItemTime';

export type GetApiModulesIdData200SensorsTvocItem = {
  time: GetApiModulesIdData200SensorsTvocItemTime;
  value: number;
};
