/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Backend API
 * API for IoT Dashboard
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiModulesIdStorage200ActiveSensorsItem } from './getApiModulesIdStorage200ActiveSensorsItem';

export type GetApiModulesIdStorage200 = {
  rowCount: number;
  estimatedSizeBytes: number;
  /** @nullable */
  oldestMeasurement: string | null;
  /** @nullable */
  newestMeasurement: string | null;
  activeSensors: GetApiModulesIdStorage200ActiveSensorsItem[];
};
