/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Backend API
 * API for IoT Dashboard
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiModulesIdStatus200HardwareChip } from './getApiModulesIdStatus200HardwareChip';

export type GetApiModulesIdStatus200Hardware = {
  chip: GetApiModulesIdStatus200HardwareChip;
};
