/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Backend API
 * API for IoT Dashboard
 * OpenAPI spec version: 1.0.0
 */

export type GetApiLogsDirection = typeof GetApiLogsDirection[keyof typeof GetApiLogsDirection];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiLogsDirection = {
  IN: 'IN',
  OUT: 'OUT',
} as const;
