/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Backend API
 * API for IoT Dashboard
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiModulesIdHistory200Eco2ItemTime } from './getApiModulesIdHistory200Eco2ItemTime';

export type GetApiModulesIdHistory200Eco2Item = {
  time: GetApiModulesIdHistory200Eco2ItemTime;
  value: number;
};
