/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Backend API
 * API for IoT Dashboard
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiModulesIdHistory200TempItemTime } from './getApiModulesIdHistory200TempItemTime';

export type GetApiModulesIdHistory200TempItem = {
  time: GetApiModulesIdHistory200TempItemTime;
  value: number;
};
