/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Backend API
 * API for IoT Dashboard
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiModulesTypesTypeManifest200HardwareItemType } from './getApiModulesTypesTypeManifest200HardwareItemType';

export type GetApiModulesTypesTypeManifest200HardwareItem = {
  key: string;
  name: string;
  type: GetApiModulesTypesTypeManifest200HardwareItemType;
  sensors: string[];
};
