/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Backend API
 * API for IoT Dashboard
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiModulesIdData200StatusSystemFlash } from './getApiModulesIdData200StatusSystemFlash';
import type { GetApiModulesIdData200StatusSystemMemory } from './getApiModulesIdData200StatusSystemMemory';

export type GetApiModulesIdData200StatusSystem = {
  /** @nullable */
  ip: string | null;
  /** @nullable */
  mac: string | null;
  /** @nullable */
  bootedAt: string | null;
  /** @nullable */
  rssi: number | null;
  flash: GetApiModulesIdData200StatusSystemFlash;
  memory: GetApiModulesIdData200StatusSystemMemory;
};
