/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Backend API
 * API for IoT Dashboard
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiModulesIdData200SensorsEco2ItemTime } from './getApiModulesIdData200SensorsEco2ItemTime';

export type GetApiModulesIdData200SensorsEco2Item = {
  time: GetApiModulesIdData200SensorsEco2ItemTime;
  value: number;
};
