/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Backend API
 * API for IoT Dashboard
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiLogs200LogsItem } from './getApiLogs200LogsItem';

export type GetApiLogs200 = {
  logs: GetApiLogs200LogsItem[];
  total: number;
  limit: number;
  offset: number;
};
