/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Backend API
 * API for IoT Dashboard
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiModulesIdData200StatusSensorsConfigSensors } from './getApiModulesIdData200StatusSensorsConfigSensors';

export type GetApiModulesIdData200StatusSensorsConfig = {
  sensors: GetApiModulesIdData200StatusSensorsConfigSensors;
};
