/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Backend API
 * API for IoT Dashboard
 * OpenAPI spec version: 1.0.0
 */

export type GetApiModulesIdStatus200SensorsConfigSensors = {[key: string]: {
  /** @nullable */
  interval: number | null;
  /** @nullable */
  model: string | null;
}};
