/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Backend API
 * API for IoT Dashboard
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiModulesIdHistory200TempShtItemTime } from './getApiModulesIdHistory200TempShtItemTime';

export type GetApiModulesIdHistory200TempShtItem = {
  time: GetApiModulesIdHistory200TempShtItemTime;
  value: number;
};
