/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Backend API
 * API for IoT Dashboard
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiModulesIdHistory200Pm4ItemTime } from './getApiModulesIdHistory200Pm4ItemTime';

export type GetApiModulesIdHistory200Pm4Item = {
  time: GetApiModulesIdHistory200Pm4ItemTime;
  value: number;
};
