/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Backend API
 * API for IoT Dashboard
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiModulesIdHistory200Pm1ItemTime } from './getApiModulesIdHistory200Pm1ItemTime';

export type GetApiModulesIdHistory200Pm1Item = {
  time: GetApiModulesIdHistory200Pm1ItemTime;
  value: number;
};
