/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Backend API
 * API for IoT Dashboard
 * OpenAPI spec version: 1.0.0
 */

export type GetApiModulesIdData200StatusHardwareChip = {
  /** @nullable */
  model: string | null;
  /** @nullable */
  rev: number | null;
  /** @nullable */
  cpuFreqMhz: number | null;
  /** @nullable */
  flashKb: number | null;
  /** @nullable */
  cores: number | null;
};
