/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Backend API
 * API for IoT Dashboard
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiModulesIdData200SensorsCo2ItemTime } from './getApiModulesIdData200SensorsCo2ItemTime';

export type GetApiModulesIdData200SensorsCo2Item = {
  time: GetApiModulesIdData200SensorsCo2ItemTime;
  value: number;
};
