/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Backend API
 * API for IoT Dashboard
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiModulesIdHistory200VocItemTime } from './getApiModulesIdHistory200VocItemTime';

export type GetApiModulesIdHistory200VocItem = {
  time: GetApiModulesIdHistory200VocItemTime;
  value: number;
};
