/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Backend API
 * API for IoT Dashboard
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiMetricsHistory200HistoryItem } from './getApiMetricsHistory200HistoryItem';

export type GetApiMetricsHistory200 = {
  history: GetApiMetricsHistory200HistoryItem[];
  count: number;
  periodDays: number;
};
