/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Backend API
 * API for IoT Dashboard
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiModulesIdHistory200Pm25ItemTime } from './getApiModulesIdHistory200Pm25ItemTime';

export type GetApiModulesIdHistory200Pm25Item = {
  time: GetApiModulesIdHistory200Pm25ItemTime;
  value: number;
};
