/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Backend API
 * API for IoT Dashboard
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiModules200ItemStatus } from './getApiModules200ItemStatus';

export type GetApiModules200Item = {
  id: string;
  name: string;
  type: string;
  /** @nullable */
  status: GetApiModules200ItemStatus;
};
