/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Backend API
 * API for IoT Dashboard
 * OpenAPI spec version: 1.0.0
 */

export type GetApiLogsCategoryAnyOfItem = typeof GetApiLogsCategoryAnyOfItem[keyof typeof GetApiLogsCategoryAnyOfItem];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiLogsCategoryAnyOfItem = {
  HARDWARE: 'HARDWARE',
  MQTT: 'MQTT',
  DB: 'DB',
  API: 'API',
  WEBSOCKET: 'WEBSOCKET',
} as const;
