/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Backend API
 * API for IoT Dashboard
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiModulesIdData200Status } from './getApiModulesIdData200Status';
import type { GetApiModulesIdData200Sensors } from './getApiModulesIdData200Sensors';

export type GetApiModulesIdData200 = {
  status: GetApiModulesIdData200Status;
  sensors: GetApiModulesIdData200Sensors;
};
