/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Backend API
 * API for IoT Dashboard
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiModulesIdStatus200SystemFlash } from './getApiModulesIdStatus200SystemFlash';
import type { GetApiModulesIdStatus200SystemMemory } from './getApiModulesIdStatus200SystemMemory';

export type GetApiModulesIdStatus200System = {
  /** @nullable */
  ip: string | null;
  /** @nullable */
  mac: string | null;
  /** @nullable */
  bootedAt: string | null;
  /** @nullable */
  rssi: number | null;
  flash: GetApiModulesIdStatus200SystemFlash;
  memory: GetApiModulesIdStatus200SystemMemory;
};
