/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Backend API
 * API for IoT Dashboard
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiModulesIdData200SensorsHumShtItemTime } from './getApiModulesIdData200SensorsHumShtItemTime';

export type GetApiModulesIdData200SensorsHumShtItem = {
  time: GetApiModulesIdData200SensorsHumShtItemTime;
  value: number;
};
