/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Backend API
 * API for IoT Dashboard
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiLogsHistogram200ItemCounts } from './getApiLogsHistogram200ItemCounts';

export type GetApiLogsHistogram200Item = {
  slot: string;
  counts: GetApiLogsHistogram200ItemCounts;
};
