/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Backend API
 * API for IoT Dashboard
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiModulesIdData200SensorsHumItemTime } from './getApiModulesIdData200SensorsHumItemTime';

export type GetApiModulesIdData200SensorsHumItem = {
  time: GetApiModulesIdData200SensorsHumItemTime;
  value: number;
};
