/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Backend API
 * API for IoT Dashboard
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiLogs200LogsItemDetails } from './getApiLogs200LogsItemDetails';

export type GetApiLogs200LogsItem = {
  id: string;
  category: string;
  source: string;
  /** @nullable */
  direction: string | null;
  level: string;
  msg: string;
  time: string;
  /** @nullable */
  details: GetApiLogs200LogsItemDetails;
};
