/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Backend API
 * API for IoT Dashboard
 * OpenAPI spec version: 1.0.0
 */

export type GetApiLogsSource = typeof GetApiLogsSource[keyof typeof GetApiLogsSource];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiLogsSource = {
  SYSTEM: 'SYSTEM',
  USER: 'USER',
} as const;
