/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Backend API
 * API for IoT Dashboard
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiModulesIdHistory200HumShtItemTime } from './getApiModulesIdHistory200HumShtItemTime';

export type GetApiModulesIdHistory200HumShtItem = {
  time: GetApiModulesIdHistory200HumShtItemTime;
  value: number;
};
