/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Backend API
 * API for IoT Dashboard
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type GetApiModules200ItemStatus = typeof GetApiModules200ItemStatus[keyof typeof GetApiModules200ItemStatus] | null;


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiModules200ItemStatus = {
  null: 'null',
} as const;
