/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Backend API
 * API for IoT Dashboard
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiModulesIdHistory200Item } from './getApiModulesIdHistory200Item';

export type GetApiModulesIdHistory200 = {[key: string]: GetApiModulesIdHistory200Item[]};
