/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Backend API
 * API for IoT Dashboard
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiModulesIdHistory200PressureItemTime } from './getApiModulesIdHistory200PressureItemTime';

export type GetApiModulesIdHistory200PressureItem = {
  time: GetApiModulesIdHistory200PressureItemTime;
  value: number;
};
