/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Backend API
 * API for IoT Dashboard
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiMetricsHistory200HistoryItemTime } from './getApiMetricsHistory200HistoryItemTime';
import type { GetApiMetricsHistory200HistoryItemDbSizeBytes } from './getApiMetricsHistory200HistoryItemDbSizeBytes';

export type GetApiMetricsHistory200HistoryItem = {
  time: GetApiMetricsHistory200HistoryItemTime;
  /** @nullable */
  codeSizeKb: number | null;
  dbSizeBytes: GetApiMetricsHistory200HistoryItemDbSizeBytes;
};
