/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Backend API
 * API for IoT Dashboard
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiModulesIdData200SensorsTempItemTime } from './getApiModulesIdData200SensorsTempItemTime';

export type GetApiModulesIdData200SensorsTempItem = {
  time: GetApiModulesIdData200SensorsTempItemTime;
  value: number;
};
