/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Backend API
 * API for IoT Dashboard
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiStorage200Database } from './getApiStorage200Database';
import type { GetApiStorage200TablesItem } from './getApiStorage200TablesItem';
import type { GetApiStorage200Measurements } from './getApiStorage200Measurements';
import type { GetApiStorage200Timescaledb } from './getApiStorage200Timescaledb';

export type GetApiStorage200 = {
  database: GetApiStorage200Database;
  tables: GetApiStorage200TablesItem[];
  measurements: GetApiStorage200Measurements;
  /** @nullable */
  timescaledb: GetApiStorage200Timescaledb;
};
