/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Backend API
 * API for IoT Dashboard
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiModulesIdData200SensorsPm25ItemTime } from './getApiModulesIdData200SensorsPm25ItemTime';

export type GetApiModulesIdData200SensorsPm25Item = {
  time: GetApiModulesIdData200SensorsPm25ItemTime;
  value: number;
};
