/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Backend API
 * API for IoT Dashboard
 * OpenAPI spec version: 1.0.0
 */

export type GetApiModulesIdData200StatusSystemFlash = {
  /** @nullable */
  usedKb: number | null;
  /** @nullable */
  freeKb: number | null;
  /** @nullable */
  systemKb: number | null;
};
