/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Backend API
 * API for IoT Dashboard
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiModulesTypesTypeManifest200HardwareItem } from './getApiModulesTypesTypeManifest200HardwareItem';
import type { GetApiModulesTypesTypeManifest200SensorsItem } from './getApiModulesTypesTypeManifest200SensorsItem';
import type { GetApiModulesTypesTypeManifest200ActionsItem } from './getApiModulesTypesTypeManifest200ActionsItem';

export type GetApiModulesTypesTypeManifest200 = {
  id: string;
  name: string;
  version: string;
  hardware: GetApiModulesTypesTypeManifest200HardwareItem[];
  sensors: GetApiModulesTypesTypeManifest200SensorsItem[];
  actions: GetApiModulesTypesTypeManifest200ActionsItem[];
};
