/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Backend API
 * API for IoT Dashboard
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiModulesIdData200SensorsPressureItemTime } from './getApiModulesIdData200SensorsPressureItemTime';

export type GetApiModulesIdData200SensorsPressureItem = {
  time: GetApiModulesIdData200SensorsPressureItemTime;
  value: number;
};
