/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Backend API
 * API for IoT Dashboard
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiModulesIdData200SensorsPm4ItemTime } from './getApiModulesIdData200SensorsPm4ItemTime';

export type GetApiModulesIdData200SensorsPm4Item = {
  time: GetApiModulesIdData200SensorsPm4ItemTime;
  value: number;
};
