/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Backend API
 * API for IoT Dashboard
 * OpenAPI spec version: 1.0.0
 */

export type GetApiModulesTypesTypeManifest200HardwareItemType = typeof GetApiModulesTypesTypeManifest200HardwareItemType[keyof typeof GetApiModulesTypesTypeManifest200HardwareItemType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiModulesTypesTypeManifest200HardwareItemType = {
  sensor: 'sensor',
  actuator: 'actuator',
} as const;
