/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Backend API
 * API for IoT Dashboard
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiModulesIdHistory200HumItemTime } from './getApiModulesIdHistory200HumItemTime';

export type GetApiModulesIdHistory200HumItem = {
  time: GetApiModulesIdHistory200HumItemTime;
  value: number;
};
