/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Backend API
 * API for IoT Dashboard
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiModulesIdHistory200Co2ItemTime } from './getApiModulesIdHistory200Co2ItemTime';

export type GetApiModulesIdHistory200Co2Item = {
  time: GetApiModulesIdHistory200Co2ItemTime;
  value: number;
};
