/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Backend API
 * API for IoT Dashboard
 * OpenAPI spec version: 1.0.0
 */

export type GetApiLogsLevelAnyOfItem = typeof GetApiLogsLevelAnyOfItem[keyof typeof GetApiLogsLevelAnyOfItem];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiLogsLevelAnyOfItem = {
  trace: 'trace',
  success: 'success',
  info: 'info',
  warn: 'warn',
  error: 'error',
  fatal: 'fatal',
} as const;
