/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Backend API
 * API for IoT Dashboard
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiModulesIdData200SensorsVocItemTime } from './getApiModulesIdData200SensorsVocItemTime';

export type GetApiModulesIdData200SensorsVocItem = {
  time: GetApiModulesIdData200SensorsVocItemTime;
  value: number;
};
