/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Backend API
 * API for IoT Dashboard
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiModulesTypesTypeManifest200SensorsItemRange } from './getApiModulesTypesTypeManifest200SensorsItemRange';

export type GetApiModulesTypesTypeManifest200SensorsItem = {
  key: string;
  label: string;
  unit: string;
  range: GetApiModulesTypesTypeManifest200SensorsItemRange;
};
