/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Backend API
 * API for IoT Dashboard
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiModulesTypesTypeManifest200ActionsItemScope } from './getApiModulesTypesTypeManifest200ActionsItemScope';

export type GetApiModulesTypesTypeManifest200ActionsItem = {
  id: string;
  label: string;
  icon: string;
  scope: GetApiModulesTypesTypeManifest200ActionsItemScope;
};
