/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Backend API
 * API for IoT Dashboard
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiModulesIdData200SensorsTemperatureBmpItemTime } from './getApiModulesIdData200SensorsTemperatureBmpItemTime';

export type GetApiModulesIdData200SensorsTemperatureBmpItem = {
  time: GetApiModulesIdData200SensorsTemperatureBmpItemTime;
  value: number;
};
