/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Backend API
 * API for IoT Dashboard
 * OpenAPI spec version: 1.0.0
 */

export type GetApiStorage200TablesItem = {
  name: string;
  totalSize: string;
  totalSizeBytes: number;
  tableSize: string;
  indexesSize: string;
};
