/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Backend API
 * API for IoT Dashboard
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiModulesIdHistory200ItemTime } from './getApiModulesIdHistory200ItemTime';

export type GetApiModulesIdHistory200Item = {
  time: GetApiModulesIdHistory200ItemTime;
  value: number;
};
