/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Backend API
 * API for IoT Dashboard
 * OpenAPI spec version: 1.0.0
 */
import type { PatchApiModulesIdPreferences200Preferences } from './patchApiModulesIdPreferences200Preferences';

export type PatchApiModulesIdPreferences200 = {
  success: boolean;
  message: string;
  preferences: PatchApiModulesIdPreferences200Preferences;
};
