/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Backend API
 * API for IoT Dashboard
 * OpenAPI spec version: 1.0.0
 */

export type PostApiModulesIdResetSensor200 = {
  success: boolean;
  message: string;
};
