/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Backend API
 * API for IoT Dashboard
 * OpenAPI spec version: 1.0.0
 */

export type PostApiModulesIdResetSensorBodySensor = typeof PostApiModulesIdResetSensorBodySensor[keyof typeof PostApiModulesIdResetSensorBodySensor];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostApiModulesIdResetSensorBodySensor = {
  co2: 'co2',
  temp: 'temp',
  temperature: 'temperature',
  humidity: 'humidity',
  voc: 'voc',
  pressure: 'pressure',
  temperature_bmp: 'temperature_bmp',
  pm1: 'pm1',
  pm25: 'pm25',
  pm4: 'pm4',
  pm10: 'pm10',
  eco2: 'eco2',
  tvoc: 'tvoc',
  temp_sht: 'temp_sht',
  hum_sht: 'hum_sht',
  all: 'all',
} as const;
